export const ROUTE_PATH = {
  HOME: '/',
  MYTEAM: '/myteam',
  MATE_LIST: '/mate-list',
  MATE_POSTING: '/mate-posting',
  MATE_DETAIL: '/mate-detail',
  LOGIN: '/login',
  SIGNUP: '/login/signup',
  NAVER_LOGIN: '/api/auth/login/naver',
  GOODS_LIST: '/goods-list',
  GOODS_POSTING: '/goods-post',
  GOODS_DETAIL: '/goods-detail',
  CHAT: '/chat',
  CHAT_MATE: '/chat?type=메이트',
  CHAT_ROOM: '/chat-room',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  FOLLOW: '/follow',
  GOODS_RECORD: '/goods-record',
  REVIEW: '/review',
  REVIEW_WRITE: '/review/write',
  TIMELINE: '/timeline',
  NOTIFICATION: '/notification',
} as const
