export const mateReviewList = [
  {
    postId: 0,
    title: '삼성 vs KT 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 1,
    title: '롯데 vs KT 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'GOOD',
    content: '뭐 같이 볼만은 했음',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 2,
    title: 'SSG vs 칰 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'GREAT',
    content: '성격 개좋네요',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 3,
    title: '삼성 vs KT 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 4,
    title: '롯데 vs KT 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'GOOD',
    content: '뭐 같이 볼만은 했음',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 5,
    title: 'SSG vs 칰 직관 가실분 구합니다',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
]

export const goodsReviewList = [
  {
    postId: 0,
    title: '쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 1,
    title: '쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'GOOD',
    content: '뭐 같이 볼만은 했음',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 2,
    title: '쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'GREAT',
    content: '성격 개좋네요',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 3,
    title: '쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 4,
    title: '쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'GOOD',
    content: '뭐 같이 볼만은 했음',
    created_at: '2024-12-01T11:45:26.211Z',
  },
  {
    postId: 5,
    title: '쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람 쁘띠 대호핑 살 사람',
    nickname: '볼빨간사촌형',
    rating: 'BAD',
    content: '이게이게 사람입니까 금수지',
    created_at: '2024-12-01T11:45:26.211Z',
  },
]
