export const mateReviewList = [
  {
    review_id: 0,
    visit_id: 0,
    reviewer_name: '볼빨간사촌형',
    review_content: '메이트 후기 텍스트',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 1,
    visit_id: 1,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 2,
    visit_id: 2,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
  {
    review_id: 3,
    visit_id: 3,
    reviewer_name: '볼빨간사촌형',
    review_content: '이게 사람입니까 두번 다시는 같이 안봅니다',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 4,
    visit_id: 4,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 5,
    visit_id: 5,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
  {
    review_id: 6,
    visit_id: 6,
    reviewer_name: '볼빨간사촌형',
    review_content: '이게 사람입니까 두번 다시는 같이 안봅니다',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 7,
    visit_id: 7,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 8,
    visit_id: 8,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
]

export const goodsReviewList = [
  {
    review_id: 0,
    visit_id: 0,
    reviewer_name: '볼빨간사촌형',
    review_content: '굿즈 거래 후기 텍스트',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 1,
    visit_id: 1,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 2,
    visit_id: 2,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
  {
    review_id: 3,
    visit_id: 3,
    reviewer_name: '볼빨간사촌형',
    review_content: '이게 사람입니까 두번 다시는 같이 안봅니다',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 4,
    visit_id: 4,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 5,
    visit_id: 5,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
  {
    review_id: 6,
    visit_id: 6,
    reviewer_name: '볼빨간사촌형',
    review_content: '이게 사람입니까 두번 다시는 같이 안봅니다',
    rating: 'BAD',
    createdAt: '2024-11-28T09:00:00',
  },
  {
    review_id: 7,
    visit_id: 7,
    reviewer_name: '덜빨간사촌형',
    review_content: '뭐 같이 볼만 했어요',
    rating: 'GOOD',
    createdAt: '2024-11-25T09:00:00',
  },
  {
    review_id: 8,
    visit_id: 8,
    reviewer_name: '개빨간북쪽형',
    review_content: '혁명적입네다',
    rating: 'GREAT',
    createdAt: '2024-11-23T09:00:00',
  },
]
